#!/bin/bash

# 进入脚本所在目录，然后返回项目根目录
scriptPath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $scriptPath
cd ../../

# Docker容器基本信息
dockerName="productservice"
dockerPort="2200"

# 编译打包
mvn clean package

# 拷贝jar包到目录
outputPath="${scriptPath}/${dockerName}";
if [ -d ${outputPath} ]; then
  rm -rf ${outputPath}
fi
mkdir ${outputPath} && mkdir ${outputPath}/jar

cp ./target/*.jar ${outputPath}/jar/app.jar
cp ${scriptPath}/release-docker.sh ${outputPath}/release-docker.sh

# 整个目录复制到应用目录中
appHome="/home/hucw/springcloud"
cd ${scriptPath}

cp -rf ./${outputPath} ${appHome}


# 挂住路径建议为绝对路径
dockerJarVolumn="${appHome}/${dockerName}"

# 停止删除现有容器
echo "停止删除容器：${dockerName}"
docker stop ${dockerName} && docker rm ${dockerName}


# Docker容器运行命令
echo ""
docker run --name=${dockerName} -d \
-p ${dockerPort}:${dockerPort} \
-v ${dockerJarVolumn}/jar:/jar \
microserv/openjdk:1.0.0


echo "${dockerName}容器已启动，使用命令查看启动日志：docker logs --tail=500 ${dockerName}"